services:
  postgres:
    container_name: postgresl-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: algo_rivals_db
    volumes:
        - postgres:/data/postgres
    ports:
        - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1081:1080
      - 1026:1025

networks:
    spring-demo:
        driver: bridge

volumes:
    postgres:
      driver: local