spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
    ##Makes it clear that all URLs starting with /api/v1/ are part of the API version 1.
