const enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",
  AUTH_USERNAME_ALREADY_EXISTS = "AUTH_USERNAME_ALREADY_EXISTS",

  // Waitlist Errors
  WAITLIST_EMAIL_ALREADY_EXISTS = "WAITLIST_EMAIL_ALREADY_EXISTS",

  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",

  // OpenAI Errors
  OPENAI_API_ERROR = "OPENAI_API_ERROR",
  OPENAI_INVALID_REQUEST = "OPENAI_INVALID_REQUEST",
  OPENAI_RATE_LIMIT_EXCEEDED = "OPENAI_RATE_LIMIT_EXCEEDED",
  OPENAI_SERVER_ERROR = "OPENAI_SERVER_ERROR",
}

export { ErrorCode };
